"""Dota 2 饰品中英文名称映射"""
ITEM_NAMES_CN = {
    # ===== 不朽 =====
    "Onibi": "鬼火",
    "Reaper's Wreath": "死神花环",
    "Arms of Desolation": "荒芜之臂",
    "The Abscesserator": "脓肿器",
    "Sullen Rampart": "阴郁壁垒",
    "Bladeform Legacy": "刀锋遗产",
    "Mantle of the Cinder Baron": "灰烬男爵披风",
    "The Resurrection of Shen - Wings": "神之复活 - 翅膀",
    "Golden Basher Blades": "纯金碎骨刃",
    "Golden Edge of the Lost Order": "纯金失落之序",
    "Golden Flopjaw": "纯金翻颌",
    "Golden Hydrakan Latch": "纯金九头蛇钩",
    "Golden Immortal - Staff of Gun-Yu": "纯金不朽 - 关羽法杖",
    "Golden Lamb of the Slaughter": "纯金屠戮之羔羊",
    "Golden Ornithomancer Mantle": "纯金恐鸟法师披风",
    "Golden Staff of Perplex": "纯金困惑之杖",
    "Golden Twilight Schism": "纯金暮光裂痕",
    "Golden Wyrmwrought Flare": "纯金龙铸之焰",
    "Golden Shen-Blessed Ring": "纯金神佑之戒",
    "Golden Ornithomancer Helmet": "纯金恐鸟法师头盔",
    "Vigil Triumph": "凯旋守望",
    "Diabolic Aspect": "恶魔面相",
    "Helm of the Scouring Terror": "恐惧之盔",
    "Crimson Pique": "深红英豪",
    "Shattered Greatsword": "破碎大剑",
    "Rain of Destiny": "命运之雨",
    "Golden Staff of the Gun-Yu": "纯金关羽法杖",
    "Golden Severing Crest": "纯金断裂徽章",
    "Golden Riptide": "纯金激流",
    "Profane Union": "渎神结合",
    "Radiant Conquest": "光辉征服",
    "Icewrack's Cube": "冰封魔方",
    "Cauldron of Xahryx": "萨里克斯之釜",
    "Latticean Shard": "拉提坎碎片",
    "Bracers of Aeon Dusk": "永恒黄昏护腕",
    "The One True Path": "唯一真理之路",
    
    # ===== 至宝 =====
    "Bladeform Legacy - Juggernaut Arcana": "剑心之遗 - 主宰至宝",
    "Fractal Horns of Inner Abysm": "深渊内心之角 - 恐怖利刃至宝",
    "Demon Eater": "噬魔者 - 影魔至宝",
    "Swine of the Sunken Galley": "沉船之豚 - 工程师至宝",
    "Exalted Fractal Horns of Inner Abysm": "尊享 深渊内心之角",
    "Manifold Paradox": "千面悖论 - 幻影刺客至宝",
    "Exalted Manifold Paradox": "尊享 千面悖论",
    "Feast of Abscession": "脓肿盛宴 - 帕吉至宝",
    "Exalted Feast of Abscession": "尊享 脓肿盛宴",
    "Benevolence of the Slom King": "史莱姆王恩赐 - 拉比克至宝",
    "Companion of the Mercenary": "佣兵之伴 - 风行者至宝",
    "Flockheart''s Gamble": "群心之赌 - 复仇之魂至宝",
    "Vile Reliquary": "邪恶圣物箱 - 冥魂大帝至宝",
    "Frost Avalanche": "冰霜雪崩 - 水晶室女至宝",
    "Exalted Frost Avalanche": "尊享 冰霜雪崩",
    "The Magus Cypher": "魔导师密码 - 祈求者至宝",
    "Exalted The Magus Cypher": "尊享 魔导师密码",
    "Claszian Apostasy": "克拉西亚叛教 - 虚空假面至宝",
    "Gothic Descent": "哥特降世 - 痛苦女王至宝",
    "Thirst of Eztzhok": "埃兹索克之渴 - 血魔至宝",
    "Demon Eater (Shadow Fiend)": "噬魔者",
    "Exalted Demon Eater": "尊享 噬魔者",
    "Eminence of Ristul": "瑞斯图之威 - 巫妖至宝",
    "Voth-Domus": "沃斯多姆 - 石鳞剑士至宝",
    "Return-Me-Not": "勿忘我 - 天怒法师至宝",
    "Lesson of the Hidden Path": "隐径之课 - 钢背兽至宝",
    "Heavy-Hearted Heist": "沉重之劫 - 力丸至宝",
    "Sublime Equidistance": "崇高等距 - 宙斯至宝",
    "The Chains of Abscession": "脓肿之链 - 帕吉至宝",

    # ===== 宝瓶套 =====
    "Mecha Boots of Travel": "机械远行鞋",

    # ===== 套装 =====
    "Sylvan Vedette": "森林哨卫",
    "Agaric Flourish": "蘑菇繁茂",
    "Vermillion Crucible": "朱红坩埚",
    "Dark Feud": "黑暗恩怨",
    "Flight of the Valkyrie": "女武神之翔",
    "Wrath of the Celestial": "天怒之怒",
    "Radiant Blossom": "光辉之花",
    "Claszian Apostasy": "克拉西亚叛教",
    
    # ===== 嘲讽 =====
    "Taunt: To Hell and Back!": "嘲讽：地狱来回！",
    "Taunt: The One Punch": "嘲讽：一拳超人",
    "Taunt: Sharp Blade": "嘲讽：利刃",
    "Taunt: Tip of the Spear": "嘲讽：矛尖",
    
    # ===== 宝箱/珍藏 =====
    "Dead Reckoning Chest": "死亡预言珍藏",
    "Immortal Treasure I": "不朽珍藏 I",
    "Immortal Treasure II": "不朽珍藏 II",
    "Immortal Treasure III": "不朽珍藏 III",
    "Collector's Cache": "典藏宝瓶",
    "Collector's Cache II": "典藏宝瓶 II",
    "Trove Carafe": "珍宝之瓶",
    "Trust of the Benefactor": "恩主之信",
    
    # ===== 棱彩/宝石 =====
    "Prismatic Gem": "棱彩宝石",
    "Ethereal Gem": "虚灵宝石",
    "Kinetic Gem": "动能宝石",
    "Inscribed Gem": "铭刻宝石",
    "Autographed": "签名",
    "Corrupted": "腐化",
    "Genuine": "纯正",
    "Heroic": "英雄",
    "Frozen": "冰霜",
    "Cursed": "诅咒",
    "Auspicious": "吉祥",
    "Elder": "远古",
    "Exalted": "尊享",
    
    # ===== 信使 =====
    "Baby Roshan": "小肉山",
    "Golden Baby Roshan": "纯金小肉山",
    "Platinum Baby Roshan": "白金小肉山",
    "Greevil": "贪魔",
    "Dreaded Greevil": "恐怖贪魔",
    "Spirited Greevil": "活跃贪魔",
    "Greedy Greevil": "贪婪贪魔",
    "Wicked Greevil": "邪恶贪魔",
    "Seraphic Greevil": "六翼贪魔",
    "Voracious Greevil": "贪食贪魔",
    "Mighty Boar": "铁鬃野猪",
    "War Dog": "战犬",
    "Trusty Mountain Yak": "忠实的雪山牦牛",
    "Speed Demon": "迅捷恶魔",
    "Skip the Delivery Frog": "蹦跳送货蛙",
    "Shagbark": "树墩",
    "Captain Bamboo": "竹节船长",
    "Itsy": "小伊奇",
    "Osky the Ottragon": "水獭龙",
    "Coco the Courageous": "勇敢的可可",
    "Arnabus the Fairy Rabbit": "仙兔阿纳布斯",
    "Beetlebark the Belligerent": "好战的甲虫树皮",
    "Mok": "莫克",
    
    # ===== 天气/地形 =====
    "Weather - Rain": "天气 - 雨天",
    "Weather - Snow": "天气 - 雪天",
    "Weather - Moonbeam": "天气 - 月光",
    "Weather - Pestilence": "天气 - 瘟疫",
    "Weather - Ash": "天气 - 灰烬",
    "Weather - Aurora": "天气 - 极光",
    "Weather - Harvest": "天气 - 收获",
    "Weather - Spring": "天气 - 春天",
    "Weather - Sirocco": "天气 - 西洛可风",
    
    # ===== 载入画面 =====
    "Loading Screen": "载入画面",
    
    # ===== 音乐包 =====
    "Music Kit": "音乐包",
    "TheFatRat": "TheFatRat",
    "Dire Shred Cover Pack": "夜魇暗潮音乐包",
    "Heroes Within Music Pack": "英雄内心音乐包",
    "TI10 Music Pack": "TI10 音乐包",
    "TI9 Music Pack": "TI9 音乐包",
    "TI8 Music Pack": "TI8 音乐包",
    "TI7 Music Pack": "TI7 音乐包",
    "TI6 Music Pack": "TI6 音乐包",
    "TI5 Music Pack": "TI5 音乐包",
    "Deadmau5": "Deadmau5",
    "Awolnation": "Awolnation",
    
    # ===== 守卫 =====
    "Ward": "守卫",
    "Wightmaw Sentry": "尸首哨兵",
    "Eye of the Ozkavosh": "奥兹卡沃什之眼",
    "Slumbering Sentinel": "沉睡哨兵",
    
    # ===== 播音员 =====
    "Announcer": "播音员",
    "Mega-Kills": "超杀配音",
    "Bastion Announcer Pack": "堡垒播音员包",
    "Stanley Parable Announcer Pack": "史丹利寓言播音员包",
    "GLaDOS Announcer Pack": "GLaDOS 播音员包",
    "Rick and Morty Announcer Pack": "瑞克和莫蒂播音员包",
    "Darkest Dungeon Announcer Pack": "暗黑地牢播音员包",
    "Fallout 4 Announcer Pack": "辐射4 播音员包",
    "Deus Ex Announcer Pack": "杀出重围 播音员包",
    "Defense Grid Announcer Pack": "防御阵型 播音员包",
    "Portal Announcer Pack": "传送门 播音员包",
    "Half-Life Announcer Pack": "半条命 播音员包",
    "Pirate Announcer": "海盗播音员",
    "Dr. Kleiner Announcer": "克莱纳博士播音员",
    "Juggernaut Announcer": "主宰播音员",
    "Axe Announcer": "斧王播音员",
    "Pudge Announcer": "帕吉播音员",
    "Storm Spirit Announcer": "风暴之灵播音员",
    "Nature's Prophet Announcer": "先知播音员",
    "Bristleback Announcer": "钢背兽播音员",
    "Techies Announcer": "工程师播音员",
    "Clockwerk Announcer": "发条技师播音员",
    "Lina Announcer": "莉娜播音员",
    "Tusk Announcer": "巨牙海民播音员",
    "Shadow Shaman Announcer": "暗影萨满播音员",
    "Kunkka & Tidehunter Announcer": "昆卡与潮汐猎人播音员",
    "Legion Commander Announcer": "军团指挥官播音员",
    "Tinker Announcer": "修补匠播音员",
    "Lone Druid Announcer": "德鲁伊播音员",
    "Phantom Lancer Announcer": "幻影长矛手播音员",
    "Bane Announcer": "祸乱之源播音员",
    
    # ===== HUD 皮肤 =====
    "HUD Skin": "HUD 皮肤",
    
    # ===== 游廊珍宝 =====
    "The International 2012": "国际邀请赛 2012",
    "The International 2013": "国际邀请赛 2013",
    "The International 2014": "国际邀请赛 2014",
    "The International 2015": "国际邀请赛 2015",
    "The International 2016": "国际邀请赛 2016",
    "The International 2017": "国际邀请赛 2017",
    "The International 2018": "国际邀请赛 2018",
    "The International 2019": "国际邀请赛 2019",
    "The International 2020": "国际邀请赛 2020",
    "The International 2021": "国际邀请赛 2021",
    "The International 2022": "国际邀请赛 2022",
    "The International 2023": "国际邀请赛 2023",
    "The International 2024": "国际邀请赛 2024",
    
    # ===== 英雄名 (作为后缀出现的) =====
    "Anti-Mage": "敌法师",
    "Axe": "斧王",
    "Bane": "祸乱之源",
    "Bloodseeker": "血魔",
    "Crystal Maiden": "水晶室女",
    "Drow Ranger": "卓尔游侠",
    "Earthshaker": "撼地者",
    "Juggernaut": "主宰",
    "Mirana": "米拉娜",
    "Morphling": "变体精灵",
    "Shadow Fiend": "影魔",
    "Phantom Lancer": "幻影长矛手",
    "Puck": "帕克",
    "Pudge": "帕吉",
    "Razor": "剃刀",
    "Sand King": "沙王",
    "Storm Spirit": "风暴之灵",
    "Sven": "斯温",
    "Tiny": "小小",
    "Vengeful Spirit": "复仇之魂",
    "Windranger": "风行者",
    "Zeus": "宙斯",
    "Kunkka": "昆卡",
    "Lina": "莉娜",
    "Lion": "莱恩",
    "Shadow Shaman": "暗影萨满",
    "Slardar": "斯拉达",
    "Tidehunter": "潮汐猎人",
    "Witch Doctor": "巫医",
    "Lich": "巫妖",
    "Riki": "力丸",
    "Enigma": "谜团",
    "Tinker": "修补匠",
    "Sniper": "狙击手",
    "Necrophos": "瘟疫法师",
    "Warlock": "术士",
    "Beastmaster": "兽王",
    "Queen of Pain": "痛苦女王",
    "Venomancer": "剧毒术士",
    "Faceless Void": "虚空假面",
    "Wraith King": "冥魂大帝",
    "Death Prophet": "死亡先知",
    "Phantom Assassin": "幻影刺客",
    "Pugna": "帕格纳",
    "Templar Assassin": "圣堂刺客",
    "Viper": "冥界亚龙",
    "Luna": "露娜",
    "Dragon Knight": "龙骑士",
    "Dazzle": "戴泽",
    "Clockwerk": "发条技师",
    "Leshrac": "拉席克",
    "Nature's Prophet": "先知",
    "Lifestealer": "噬魂鬼",
    "Dark Seer": "黑暗贤者",
    "Clinkz": "克林克兹",
    "Omniknight": "全能骑士",
    "Enchantress": "魅惑魔女",
    "Huskar": "哈斯卡",
    "Night Stalker": "暗夜魔王",
    "Broodmother": "育母蜘蛛",
    "Bounty Hunter": "赏金猎人",
    "Weaver": "编织者",
    "Jakiro": "杰奇洛",
    "Batrider": "蝙蝠骑士",
    "Chen": "陈",
    "Spectre": "幽鬼",
    "Ancient Apparition": "远古冰魄",
    "Doom": "末日使者",
    "Ursa": "熊战士",
    "Spirit Breaker": "裂魂人",
    "Gyrocopter": "直升机",
    "Alchemist": "炼金术士",
    "Invoker": "祈求者",
    "Silencer": "沉默术士",
    "Outworld Devourer": "殁境神蚀者",
    "Lycan": "狼人",
    "Brewmaster": "酒仙",
    "Shadow Demon": "暗影恶魔",
    "Lone Druid": "德鲁伊",
    "Chaos Knight": "混沌骑士",
    "Meepo": "米波",
    "Treant Protector": "树精卫士",
    "Ogre Magi": "食人魔魔法师",
    "Undying": "不朽尸王",
    "Rubick": "拉比克",
    "Disruptor": "干扰者",
    "Nyx Assassin": "司夜刺客",
    "Naga Siren": "娜迦海妖",
    "Keeper of the Light": "光之守卫",
    "Io": "艾欧",
    "Visage": "维萨吉",
    "Slark": "斯拉克",
    "Medusa": "美杜莎",
    "Troll Warlord": "巨魔战将",
    "Centaur Warrunner": "半人马战行者",
    "Magnus": "马格纳斯",
    "Timbersaw": "伐木机",
    "Bristleback": "钢背兽",
    "Tusk": "巨牙海民",
    "Skywrath Mage": "天怒法师",
    "Abaddon": "亚巴顿",
    "Elder Titan": "上古巨神",
    "Legion Commander": "军团指挥官",
    "Techies": "工程师",
    "Ember Spirit": "灰烬之灵",
    "Earth Spirit": "大地之灵",
    "Underlord": "孽主",
    "Terrorblade": "恐怖利刃",
    "Phoenix": "凤凰",
    "Oracle": "神谕者",
    "Winter Wyvern": "寒冬飞龙",
    "Arc Warden": "天穹守望者",
    "Monkey King": "齐天大圣",
    "Dark Willow": "邪影芳灵",
    "Pangolier": "石鳞剑士",
    "Grimstroke": "天涯墨客",
    "Mars": "玛尔斯",
    "Hoodwink": "森海飞霞",
    "Void Spirit": "虚无之灵",
    "Snapfire": "电炎绝手",
    "Dawnbreaker": "破晓辰星",
    "Marci": "玛西",
    "Primal Beast": "原力野兽",
    "Muerta": "亡灵射手",
    "Ringmaster": "马戏团长",
    "Kez": "凯兹",
}

def get_cn_name(market_hash_name: str) -> str:
    """根据 market_hash_name 获取中文名"""
    if not market_hash_name:
        return ""
    
    # 精确匹配
    if market_hash_name in ITEM_NAMES_CN:
        return ITEM_NAMES_CN[market_hash_name]
    
    # 尝试提取核心名称（去除前缀英雄名等）
    # 很多饰品格式为 "英雄名's Item Name" 或 "Item Name - Slot"
    for en, cn in ITEM_NAMES_CN.items():
        if en.lower() in market_hash_name.lower():
            return market_hash_name.replace(en, cn)
    
    return market_hash_name
